#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef TAGWORKS_SDK_IOS_V1_SWIFT_H
#define TAGWORKS_SDK_IOS_V1_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="TagWorks_SDK_iOS_v1",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
/// 사용자 정의 이벤트 저장을 위한 클래스입니다.
/// Dimension은 서버에서 정의해 놓은 Map 형태의 테이블이 존재하기에 그에 따름.
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v110DataBundle")
@interface DataBundle : NSObject
/// 초기화 함수
/// 사용자 정의 기본 생성자입니다.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(DataBundle * _Nonnull)bundle;
/// 파라미터 추가
/// 이벤트에 필요한 파라미터 항목들을, Key, Value의 String 형태로 Dictionary에 추가
- (void)putString:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
/// 파라미터 제거
/// 이벤트에 필요한 파라미터 항목들 중에 해당 키 항목을 제거
- (void)removeForKey:(NSString * _Nonnull)key;
/// 이벤트에 필요한 파라미터 항목들이 비어 있는지 체크
- (BOOL)isParameterEmpty SWIFT_WARN_UNUSED_RESULT;
/// 이벤트에 필요한 Dimension 항목들이 비어 있는지 체크
- (BOOL)isDimensionEmpty SWIFT_WARN_UNUSED_RESULT;
/// 이벤트에 필요한 파라미터 항목들의 갯수를 리턴
- (NSInteger)parameterCount SWIFT_WARN_UNUSED_RESULT;
/// 이벤트에 필요한 Dimension 항목들의 갯수를 리턴
- (NSInteger)dimensionCount SWIFT_WARN_UNUSED_RESULT;
@end

@interface DataBundle (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
/// Event 항목 정의
/// Event Key
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_NAME;)
+ (NSString * _Nonnull)EVENT_TAG_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PARAM_TITLE;)
+ (NSString * _Nonnull)EVENT_TAG_PARAM_TITLE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PARAM_PAGE_PATH;)
+ (NSString * _Nonnull)EVENT_TAG_PARAM_PAGE_PATH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PARAM_KEYWORD;)
+ (NSString * _Nonnull)EVENT_TAG_PARAM_KEYWORD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PARAM_CUSTOM_PATH;)
+ (NSString * _Nonnull)EVENT_TAG_PARAM_CUSTOM_PATH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TAG_PARAM_ERROR_MSG;)
+ (NSString * _Nonnull)EVENT_TAG_PARAM_ERROR_MSG SWIFT_WARN_UNUSED_RESULT;
@end

@class Dimension;
@interface DataBundle (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
/// 이벤트에 필요한 Dimension 항목들을, Array에 추가
/// 단, 추가하기 전 중복 항목 체크..
- (void)putDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
/// 수집 로그의 개별 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimension 추가할 디멘전 객체
///
- (void)putDimensionWithDimension:(Dimension * _Nonnull)dimension;
- (void)putDimension:(Dimension * _Nonnull)dimension;
/// 수집 로그의 개별 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param stringValue 추가할 디멘전 value (d - String 타입)
///
- (void)putDimensionWithIndex:(NSInteger)index stringValue:(NSString * _Nonnull)stringValue;
- (void)putDimensionWithIndex:(NSInteger)index value:(NSString * _Nonnull)value;
/// 수집 로그의 개별 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param numValue 추가할 디멘전 value (f - Double 타입)
///
- (void)putDimensionWithIndex:(NSInteger)index numValue:(double)numValue;
/// 이벤트 디멘전을 가져옵니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (Dimension * _Nullable)getDimensionWithType:(NSInteger)type index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Dimension *> * _Nonnull)getDimensions SWIFT_WARN_UNUSED_RESULT;
/// 해당 index의 Dimension을 삭제
/// \param index 삭제할 디멘전 index
///
- (void)removeDimensionWithType:(NSInteger)type index:(NSInteger)index;
- (void)removeDimensionWithArrayIndex:(NSInteger)index;
- (void)removeAllDimension;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimensions 추가할 디멘전 배열 객체
///
- (void)putDynamicDimensionWithDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
- (void)putDynamicDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimension 추가할 디멘전 객체
///
- (void)putDynamicDimensionWithDimension:(Dimension * _Nonnull)dimension;
- (void)putDynamicDimension:(Dimension * _Nonnull)dimension;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param stringValue 추가할 디멘전 value (d - String 타입)
///
- (void)putDynamicDimensionWithKey:(NSString * _Nonnull)key stringValue:(NSString * _Nonnull)stringValue;
- (void)putDynamicDimensionWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param numValue 추가할 디멘전 value (f - Double 타입)
///
- (void)putDynamicDimensionWithKey:(NSString * _Nonnull)key numValue:(double)numValue;
/// 수집 로그의 공용 디멘전을 제거합니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (void)removeDynamicDimensionWithKey:(NSString * _Nonnull)key;
- (void)removeDynamicDimensionWithArrayIndex:(NSInteger)index;
- (void)removeAllDynamicDimension;
/// 수집 로그의 공용 디멘전을 가져옵니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (Dimension * _Nullable)getDynamicDimensionWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Dimension *> * _Nonnull)getDynamicDimensions SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v115DeeplinkManager")
@interface DeeplinkManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) DeeplinkManager * _Nonnull sharedInstance;)
+ (DeeplinkManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum LogLevel : NSInteger;
/// Logger 클래스의 인터페이스입니다.
SWIFT_PROTOCOL("_TtP19TagWorks_SDK_iOS_v16Logger_")
@protocol Logger
- (void)log:(SWIFT_NOESCAPE NSString * _Nonnull (^ _Nonnull)(void))message with:(enum LogLevel)level file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
@end

/// 런타임 로그 발생을 위한 Logger 인터페이스를 상속받는 구현체 클래스 입니다.
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v113DefaultLogger")
@interface DefaultLogger : NSObject <Logger>
/// 런타임 로거 클래스의 기본 생성자입니다.
/// \param minLevel 로그 레벨
///
- (nonnull instancetype)initWithMinLevel:(enum LogLevel)minLevel OBJC_DESIGNATED_INITIALIZER;
/// 런타임 로그를 입력받아 콘솔에 로그를 출력합니다.
/// Protocol 구현부
/// \param message 로그 메시지
///
/// \param level 로그 레벨
///
/// \param file 로그 파일
///
/// \param function 로그 함수
///
/// \param line 로그 라인
///
- (void)log:(SWIFT_NOESCAPE NSString * _Nonnull (^ _Nonnull)(void))message with:(enum LogLevel)level file:(NSString * _Nonnull)file function:(NSString * _Nonnull)function line:(NSInteger)line;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 이벤트 구조체를 저장하는 Queue 인터페이스를 상속받는 구현체 클래스입니다.
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v112DefaultQueue")
@interface DefaultQueue : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// 사용자 정의 디멘전 저장을 위한 클래스입니다.
/// Dimension은 서버에서 정의해 놓은 Map 형태의 테이블이 존재하기에 그에 따름.
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v19Dimension")
@interface Dimension : NSObject
/// 사용자 정의 디멘전의 index
@property (nonatomic, readonly) NSInteger index;
/// 동적 파라미터에서 사용하기 위한 Key
@property (nonatomic, readonly, copy) NSString * _Nonnull key;
/// 사용자 정의 디멘전의 value
@property (nonatomic, readonly, copy) NSString * _Nonnull value;
/// fact
@property (nonatomic, readonly) double numValue;
/// type
@property (nonatomic) NSInteger type;
/// 사용자 정의 디멘전의 기본 생성자입니다.
/// \param type 사용자 정의 디멘전의 Type (general, fact)
///
/// \param index 사용자 정의 디멘전의 index
///
/// \param numValue 사용자 정의 디멘전의 fact value
///
/// \param stringValue 사용자 정의 디멘전의 string value
///
- (nonnull instancetype)initWithType:(NSInteger)type index:(NSInteger)index stringValue:(NSString * _Nonnull)stringValue numValue:(double)numValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIndex:(NSInteger)index stringValue:(NSString * _Nonnull)stringValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIndex:(NSInteger)index value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithIndex:(NSInteger)index numValue:(double)numValue OBJC_DESIGNATED_INITIALIZER;
/// 동적 파라미터를 이용한 Dimension 설정
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithKey:(NSString * _Nonnull)key numValue:(double)numValue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, DimensionType, open) {
  DimensionTypeIndexed = 0,
  DimensionTypeDynamic = 1,
};

@interface Dimension (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
/// 입력받는 Dimension의 Type을 정의
/// Codable Protocol을 준수하기 위해 static 일반 변수로 정의 후 사용토록 함.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger generalType;)
+ (NSInteger)generalType SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger factType;)
+ (NSInteger)factType SWIFT_WARN_UNUSED_RESULT;
@end

/// 태그 이벤트 트리거를 열거합니다.
/// EVENT_TAG_NAME 키 사용에 들어갈 Standard Tag 값
typedef SWIFT_ENUM(NSInteger, EventTag, open) {
  EventTagPAGE_VIEW = 10,
  EventTagCLICK = 20,
  EventTagSCROLL = 30,
  EventTagDOWNLOAD = 40,
  EventTagOUT_LINK = 50,
  EventTagSEARCH = 60,
  EventTagERROR = 70,
  EventTagREFERRER = 80,
  EventTagBACKGROUND = 90,
  EventTagFOREGROUND = 100,
  EventTagDEEPLINK = 110,
  EventTagAPP_PUSH = 120,
};

@class WKWebView;
@class WKNavigation;
@class WKUserContentController;
@class WKScriptMessage;
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v118FingerprintManager")
@interface FingerprintManager : NSObject <WKNavigationDelegate, WKScriptMessageHandler>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, InAppPopupButtonType, open) {
  InAppPopupButtonTypeNone = 0,
  InAppPopupButtonTypeClose = 1,
  InAppPopupButtonTypeCloseAndNoMoreShow = 2,
  InAppPopupButtonTypeCloseAndNoShowToday = 3,
  InAppPopupButtonTypeCloseAndNoShowSeven = 4,
};

typedef SWIFT_ENUM(NSInteger, InAppPopupType, open) {
  InAppPopupTypeCenter = 1,
  InAppPopupTypeBottom = 2,
  InAppPopupTypePage = 3,
  InAppPopupTypeTop = 4,
};

/// TagWorks Logger 의 로그 레벨을 열거합니다.
typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
  LogLevelVerbose = 10,
  LogLevelDebug = 20,
  LogLevelInfo = 30,
  LogLevelWarning = 40,
  LogLevelError = 50,
};

/// Objective-C
/// // Objective-C에서 사용할 EventTag Class
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v116StandardEventTag")
@interface StandardEventTag : NSObject
+ (NSString * _Nonnull)toStringWithEventTag:(enum EventTag)eventTag SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PAGE_VIEW;)
+ (NSString * _Nonnull)PAGE_VIEW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CLICK;)
+ (NSString * _Nonnull)CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SCROLL;)
+ (NSString * _Nonnull)SCROLL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DOWNLOAD;)
+ (NSString * _Nonnull)DOWNLOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull OUT_LINK;)
+ (NSString * _Nonnull)OUT_LINK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SEARCH;)
+ (NSString * _Nonnull)SEARCH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ERROR;)
+ (NSString * _Nonnull)ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REFERRER;)
+ (NSString * _Nonnull)REFERRER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BACKGROUND;)
+ (NSString * _Nonnull)BACKGROUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull FOREGROUND;)
+ (NSString * _Nonnull)FOREGROUND SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEEPLINK;)
+ (NSString * _Nonnull)DEEPLINK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull APP_PUSH;)
+ (NSString * _Nonnull)APP_PUSH SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
@class WebInterface;
@class UIButton;
/// TagWorks 클래스는 SDK 모듈내에서 가장 최상위에 존재하는 클래스입니다.
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v18TagWorks")
@interface TagWorks : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TagWorks * _Nonnull sharedInstance;)
+ (TagWorks * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Logger 객체입니다.
@property (nonatomic, strong) id <Logger> _Nonnull logger;
/// 수집되는 사용자의 방문자 식별자입니다.
/// 현재 유효한 사용자의 방문자 식별자를 반환합니다.
/// <ul>
///   <li>
///     최초로 수집되어 방문자 식별자가 없는 경우 신규 ID를 발급합니다.
///   </li>
///   <li>
///     생성된 방문자 식별자는 UUID를 기반으로 하며 소문자로 발급됩니다.
///   </li>
/// </ul>
/// <ul>
///   <li>
///     해당 디바이스의 고유 식별자입니다. (UUID를 사용하나 바뀌지 않는것이 좋음)
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nonnull visitorId;
/// 수집되는 사용자의 유저 식별자 (고객 식별자)입니다.
/// <ul>
///   <li>
///     로그인되어 사용하는 사용자의 유저 식별자입니다. (사이트에서 전달받음)
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nullable userId;
/// 수집 허용 여부 입니다.
@property (nonatomic) BOOL isOptedOut;
/// 수집되는 사용자의 App Version입니다.
/// <ul>
///   <li>
///     값이 없을 경우에는 내부적으로 Short Version을 사용합니다.
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nullable appVersion;
/// 수집되는 사용자의 App 이름입니다.
/// <ul>
///   <li>
///     값이 없을 경우에는 내부적으로 Display Bundle Name을 사용합니다.
///   </li>
/// </ul>
@property (nonatomic, copy) NSString * _Nullable appName;
/// 수집되는 사용자 Device의 IDFA(광고식별자)
@property (nonatomic) BOOL isEnabledAdId;
@property (nonatomic, copy) NSString * _Nullable adId;
- (void)setAdid:(NSString * _Nonnull)uuid;
@property (nonatomic, copy) NSString * _Nullable pushToken;
- (void)setDevicePushToken:(NSString * _Nonnull)token;
/// 수집되는 어플리케이션의 기본 Url 주소입니다.
/// <ul>
///   <li>
///     수집대상이 되는 어플리케이션의 bundleIdentifier 주소를 기본으로 하며, 별도 지정시 지정된 값으로 수집됩니다.
///   </li>
/// </ul>
@property (nonatomic, copy) NSURL * _Nullable contentUrl;
/// 수집되는 어플리케이션의 현재 Url 주소입니다.
/// <ul>
///   <li>
///     PageView 이벤트 호출시 contentUrl + 지정된 Url 경로 순으로 수집됩니다.
///   </li>
/// </ul>
@property (nonatomic, copy) NSURL * _Nullable currentContentUrlPath;
/// SDK 디버깅을 위한 로그 출력 플래그
/// 디폴트는 출력을 하지 않으나, 이슈 발생 시 true로 셋팅 하여 디버깅 로그를 통해 SDK 플로우를 디버깅
@property (nonatomic) BOOL isDebugLogPrint;
@property (nonatomic) BOOL isDebugLogPost;
@property (nonatomic) BOOL isManualDispatch;
@property (nonatomic) BOOL isUseDynamicParameter;
/// 웹뷰로부터 자바스크립트로 웹뷰 이벤트를 전달받아 처리하는 클래스 객체
@property (nonatomic, readonly, strong) WebInterface * _Nonnull webViewInterface;
@property (nonatomic) BOOL isDispatchRetry;
/// Interval을 사용할 경우, 앱이 예기치 않은 종료로 인해 큐에 이벤트가 남아있을 때 앱 시작 시 발송하지 못한 이벤트를 전송 - by Kevin. 2025.04.28
@property (nonatomic) BOOL localQueueEnabled;
/// 앱이 비정상 종료 시 인터페이스를 통해 에러 로그를 저장 및 앱 재실행 시 에러 로그 전송 - by Kevin. 2025.05.12
@property (nonatomic) BOOL errorReportEnabled;
@property (nonatomic) BOOL autoTrackingPage;
@property (nonatomic) BOOL autoTrackingButtonClick;
@property (nonatomic) BOOL autoTrackingApplication;
@property (nonatomic) BOOL autoTrackingScene;
/// 이벤트 전송에 필요한 필수 항목 입력
/// \param siteId 수집 대상이 되는 사이트(고객사) 식별자
///
/// \param baseUrl 수집 로그 발송을 위한 서버 URL
///
/// \param userAgent 수집 대상의 userAgent 객체 String
///
- (void)setInstanceConfigWithSiteId:(NSString * _Nonnull)siteId baseUrl:(NSURL * _Nonnull)baseUrl isUseIntervals:(BOOL)isUseIntervals dispatchInterval:(NSTimeInterval)dispatchInterval userAgent:(NSString * _Nullable)userAgent appVersion:(NSString * _Nullable)appVersion appName:(NSString * _Nullable)appName;
/// 이벤트 전송에 필요한 필수 항목 입력
/// 1.1.10 버전 이후 추가 - 파라미터에 sesstionTimeOut 값 추가
/// \param siteId 수집 대상이 되는 사이트(고객사) 식별자
///
/// \param baseUrl 수집 로그 발송을 위한 서버 URL
///
/// \param userAgent 수집 대상의 userAgent 객체 String
///
- (void)setInstanceConfigWithSiteId:(NSString * _Nonnull)siteId baseUrl:(NSURL * _Nonnull)baseUrl isUseIntervals:(BOOL)isUseIntervals dispatchInterval:(NSTimeInterval)dispatchInterval sessionTimeOut:(NSTimeInterval)sessionTimeOut userAgent:(NSString * _Nullable)userAgent appVersion:(NSString * _Nullable)appVersion appName:(NSString * _Nullable)appName;
/// 이벤트 전송에 필요한 필수 항목 입력
/// 1.1.22 버전 이후 추가 - 파라미터에 isUseDynamicParameter 값 추가
/// \param siteId 수집 대상이 되는 사이트(고객사) 식별자
///
/// \param baseUrl 수집 로그 발송을 위한 서버 URL
///
/// \param userAgent 수집 대상의 userAgent 객체 String
///
- (void)setInstanceConfigWithSiteId:(NSString * _Nonnull)siteId baseUrl:(NSURL * _Nonnull)baseUrl isUseIntervals:(BOOL)isUseIntervals dispatchInterval:(NSTimeInterval)dispatchInterval sessionTimeOut:(NSTimeInterval)sessionTimeOut userAgent:(NSString * _Nullable)userAgent isManualDispatch:(BOOL)isManualDispatch appVersion:(NSString * _Nullable)appVersion appName:(NSString * _Nullable)appName isUseDynamicParameter:(BOOL)isUseDynamicParameter isEnabledAdId:(BOOL)isEnabledAdId;
/// 이벤트 전송에 필요한 필수 항목 입력
/// \param siteId 수집 대상이 되는 사이트(고객사) 식별자
///
/// \param baseUrl 수집 로그 발송을 위한 서버 URL
///
/// \param userAgent 수집 대상의 userAgent 객체 String
///
- (void)setInstanceConfigWithSiteId:(NSString * _Nonnull)siteId baseUrl:(NSURL * _Nonnull)baseUrl isUseIntervals:(BOOL)isUseIntervals dispatchIntervalWithSeconds:(NSTimeInterval)dispatchIntervalWithSeconds sessionTimeOutWithSeconds:(NSTimeInterval)sessionTimeOutWithSeconds userAgent:(NSString * _Nullable)userAgent isManualDispatch:(BOOL)isManualDispatch appVersion:(NSString * _Nullable)appVersion appName:(NSString * _Nullable)appName isUseDynamicParameter:(BOOL)isUseDynamicParameter isEnabledAdId:(BOOL)isEnabledAdId deeplinkServerUrl:(NSURL * _Nullable)deeplinkServerUrl;
/// 이벤트 전송에 필요한 필수 항목 입력
/// 1.1.28 버전 이후 제거 - 파라미터에 userAgent 값 제거
/// isUseDynamicParameter 디폴트 값을 true로 설정
/// \param siteId 수집 대상이 되는 사이트(고객사) 식별자
///
/// \param baseUrl 수집 로그 발송을 위한 서버 URL
///
/// \param userAgent 수집 대상의 userAgent 객체 String
///
- (void)setInstanceConfigWithSiteId:(NSString * _Nonnull)siteId baseUrl:(NSURL * _Nonnull)baseUrl isUseIntervals:(BOOL)isUseIntervals dispatchIntervalWithSeconds:(NSTimeInterval)dispatchIntervalWithSeconds sessionTimeOutWithSeconds:(NSTimeInterval)sessionTimeOutWithSeconds isManualDispatch:(BOOL)isManualDispatch appVersion:(NSString * _Nullable)appVersion appName:(NSString * _Nullable)appName isUseDynamicParameter:(BOOL)isUseDynamicParameter isEnabledAdId:(BOOL)isEnabledAdId deeplinkServerUrl:(NSURL * _Nullable)deeplinkServerUrl;
- (void)setManualDispatch:(BOOL)isManual;
- (void)clearUserId;
- (void)excludeAutoTrackingPages:(NSArray<Class> * _Nonnull)pageClasses;
- (void)registerButtons:(NSArray<UIButton *> * _Nonnull)buttons;
/// 딥링크나 푸시를 통해 앱이 실행이 된 경우, 파라미터를 받아서 파싱 후 분석하여 로그 수집
- (void)launchWithOptionsWithUrl:(NSURL * _Nullable)url userInfo:(NSDictionary * _Nullable)userInfo;
/// 딥링크로 앱이 실행이 된 경우, 앱에서 등록한 콜백 함수를 통해 앱의 랜딩 페이지로 이동시킴
- (void)registerDeeplinkCallback:(void (^ _Nonnull)(BOOL, NSURL * _Nonnull))callback;
/// 현재 Queue에 저장되어 있는 이벤트 구조체를 즉시 발송합니다. (수동 처리)
- (BOOL)dispatch SWIFT_WARN_UNUSED_RESULT;
@end

@interface TagWorks (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
- (void)saveErrorReportWithErrorType:(NSString * _Nonnull)errorType errorMessage:(NSString * _Nonnull)errorMessage;
@end

@interface TagWorks (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
- (void)sendReferrerEventWithOpenURL:(NSURL * _Nonnull)openURL;
- (void)sendReferrerEventWithReferrer:(NSString * _Nonnull)referrer;
@end

@interface TagWorks (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
- (BOOL)isInitialize SWIFT_WARN_UNUSED_RESULT;
/// Dictionary 형태의 DataBundle로 파라미터들을 받기 위해 새로 구현 - Added by Kevin 2024.07.22
- (BOOL)logEvent:(NSString * _Nonnull)type bundle:(DataBundle * _Nonnull)bundle SWIFT_WARN_UNUSED_RESULT;
@end

@interface TagWorks (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
/// 필수 파라미터 정의
/// <ol>
///   <li>
///     EVENT_TYPE_PAGE
///   </li>
/// </ol>
/// <ul>
///   <li>
///     EVENT_TAG_NAME
///   </li>
///   <li>
///     EVENT_TAG_PARAM_TITLE
///   </li>
///   <li>
///     EVENT_TAG_PARAM_PAGE_PATH
///   </li>
/// </ul>
/// <ol>
///   <li>
///     EVENT_TYPE_USER_EVENT
///   </li>
/// </ol>
/// <ul>
///   <li>
///     EVENT_TAG_NAME
///   </li>
///   <li>
///     <h1>EVENT_TAG_NAME 이 EventTag.search.description 인 경우,</h1>
///   </li>
/// </ul>
/// –> EVENT_TAG_PARAM_KEYWORD
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TYPE_PAGE;)
+ (NSString * _Nonnull)EVENT_TYPE_PAGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TYPE_USER_EVENT;)
+ (NSString * _Nonnull)EVENT_TYPE_USER_EVENT SWIFT_WARN_UNUSED_RESULT;
@end

@interface TagWorks (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1))
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimensions 추가할 디멘전 배열 객체
///
- (void)setCommonDimensionWithDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
- (void)setCommonDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimension 추가할 디멘전 객체
///
- (void)setCommonDimensionWithDimension:(Dimension * _Nonnull)dimension;
- (void)setCommonDimension:(Dimension * _Nonnull)dimension;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param stringValue 추가할 디멘전 value (d - String 타입)
///
- (void)setCommonDimensionWithIndex:(NSInteger)index stringValue:(NSString * _Nonnull)stringValue;
- (void)setCommonDimensionWithIndex:(NSInteger)index value:(NSString * _Nonnull)value;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param numValue 추가할 디멘전 value (f - Double 타입)
///
- (void)setCommonDimensionWithIndex:(NSInteger)index numValue:(double)numValue;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param type 추가할 디멘전 type
///
/// \param index 추가할 디멘전 index
///
/// \param stringValue 추가할 디멘전 value (d - String 타입)
///
/// \param numValue 추가할 디멘전 value (f - Double 타입)
///
- (void)setCommonDimensionWithType:(NSInteger)type index:(NSInteger)index stringValue:(NSString * _Nonnull)stringValue numValue:(double)numValue;
/// 수집 로그의 공용 디멘전을 제거합니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (void)removeCommonDimensionWithType:(NSInteger)type index:(NSInteger)index;
- (void)removeCommonDimensionWithArrayIndex:(NSInteger)index;
- (void)removeAllCommonDimension;
/// 수집 로그의 공용 디멘전을 가져옵니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (Dimension * _Nullable)getCommonDimensionWithType:(NSInteger)type index:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Dimension *> * _Nonnull)getCommonDimensions SWIFT_WARN_UNUSED_RESULT;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimensions 추가할 디멘전 배열 객체
///
- (void)setDynamicCommonDimensionWithDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
- (void)setDynamicCommonDimensions:(NSArray<Dimension *> * _Nonnull)dimensions;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param dimension 추가할 디멘전 객체
///
- (void)setDynamicCommonDimensionWithDimension:(Dimension * _Nonnull)dimension;
- (void)setDynamicCommonDimension:(Dimension * _Nonnull)dimension;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param stringValue 추가할 디멘전 value (d - String 타입)
///
- (void)setDynamicCommonDimensionWithKey:(NSString * _Nonnull)key stringValue:(NSString * _Nonnull)stringValue;
- (void)setDynamicCommonDimensionWithKey:(NSString * _Nonnull)key value:(NSString * _Nonnull)value;
/// 수집 로그의 공용 디멘전을 지정합니다.
/// <ul>
///   <li>
///     이미 동일한 인덱스에 지정된 디멘전이 있는 경우 삭제하고 저장됩니다.
///   </li>
/// </ul>
/// \param index 추가할 디멘전 index
///
/// \param numValue 추가할 디멘전 value (f - Double 타입)
///
- (void)setDynamicCommonDimensionWithKey:(NSString * _Nonnull)key numValue:(double)numValue;
/// 수집 로그의 공용 디멘전을 제거합니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (void)removeDynamicCommonDimensionWithKey:(NSString * _Nonnull)key;
- (void)removeDynamicCommonDimensionWithArrayIndex:(NSInteger)index;
- (void)removeAllDynamicCommonDimension;
/// 수집 로그의 공용 디멘전을 가져옵니다.
/// <ul>
///   <li>
///     Parameters:
///   </li>
///   <li>
///     WithType: 디멘전 type
///   </li>
///   <li>
///     index: 디멘전 index
///   </li>
/// </ul>
- (Dimension * _Nullable)getDynamicCommonDimensionWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSArray<Dimension *> * _Nonnull)getDynamicCommonDimensions SWIFT_WARN_UNUSED_RESULT;
@end

@class UIViewController;
@class UIView;
@class UINavigationController;
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v113TagWorksPopup")
@interface TagWorksPopup : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) TagWorksPopup * _Nonnull sharedInstance;)
+ (TagWorksPopup * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)onCMSPopupOnCmsUrl:(NSString * _Nonnull)onCmsUrl cust_id:(NSString * _Nonnull)cust_id rcmd_area_cd:(NSString * _Nonnull)rcmd_area_cd owner:(UIViewController * _Nonnull)owner;
- (void)onCMSPopupOnCmsUrl:(NSString * _Nonnull)onCmsUrl cntn_id:(NSString * _Nonnull)cntn_id cust_id:(NSString * _Nonnull)cust_id rcmd_area_cd:(NSString * _Nonnull)rcmd_area_cd owner:(UIViewController * _Nonnull)owner;
- (void)onCMSPopupBannerOnCmsUrl:(NSString * _Nonnull)onCmsUrl cust_id:(NSString * _Nonnull)cust_id rcmd_area_cd:(NSString * _Nonnull)rcmd_area_cd bannerView:(UIView * _Nonnull)bannerView defaultPngImageName:(NSString * _Nonnull)defaultPngImageName;
- (void)setWebViewDefaultContentsWithWebView:(WKWebView * _Nonnull)webView pngImageName:(NSString * _Nonnull)pngImageName;
- (void)presentDetailWebViewcontrollerWithLoadUrl:(NSString * _Nonnull)loadUrl owner:(UIViewController * _Nonnull)owner;
- (void)pushDetailWebViewcontrollerWithLoadUrl:(NSString * _Nonnull)loadUrl owner:(UINavigationController * _Nonnull)owner;
@end

/// 웹브라우저를 통해 간단하게 UserAgent를 가져오기
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v116UserAgentFetcher")
@interface UserAgentFetcher : NSObject <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v112WebInterface")
@interface WebInterface : NSObject <WKScriptMessageHandler>
@property (nonatomic, readonly, copy) NSString * _Nonnull messageHandlerName;
@property (nonatomic, readonly, copy) NSString * _Nonnull omCmsPopupHandlerName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// WKWebView의 WKWebViewConfiguration에서 사용할 WKUserContentController 객체를 전달
/// <ul>
///   <li>
///     WKUserContentController 내에 인터페이스 이름과 메세지를 받을 target을 지정한 뒤 해당 객체를 리턴
///   </li>
/// </ul>
- (WKUserContentController * _Nonnull)getContentController SWIFT_WARN_UNUSED_RESULT;
/// WKWebView의 WKWebViewConfiguration에서 사용할 WKUserContentController 객체를 전달받아 Script Interface 연결
- (void)addTagworksWebInterface:(WKUserContentController * _Nonnull)contentController;
/// 실제로 WebView Javascript에서 호출한 메세지 핸들러를 처리하는 부분
/// 웹뷰에서만 쓰는 고유 Key 값 : tag_id (서버에서는 바이패스)
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
- (void)webInterfaceDidReceiveDictionary:(NSDictionary<NSString *, id> * _Nonnull)msgDictionary;
- (void)webInterfaceDidReceiveOnCmsPopupDictionary:(NSDictionary<NSString *, id> * _Nonnull)msgDictionary;
@end

@class NSCoder;
@class NSBundle;
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v122WebPopupViewController")
@interface WebPopupViewController : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class WKFrameInfo;
SWIFT_AVAILABILITY(ios,introduced=13.0.0)
@interface WebPopupViewController (SWIFT_EXTENSION(TagWorks_SDK_iOS_v1)) <WKUIDelegate>
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptAlertPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (void)webView:(WKWebView * _Nonnull)webView runJavaScriptConfirmPanelWithMessage:(NSString * _Nonnull)message initiatedByFrame:(WKFrameInfo * _Nonnull)frame completionHandler:(void (^ _Nonnull)(BOOL))completionHandler;
@end

@class WKNavigationAction;
@class WKNavigationResponse;
SWIFT_CLASS("_TtC19TagWorks_SDK_iOS_v114WebViewManager")
@interface WebViewManager : NSObject <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView didStartProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView didReceiveServerRedirectForProvisionalNavigation:(WKNavigation * _Null_unspecified)navigation;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationResponse:(WKNavigationResponse * _Nonnull)navigationResponse decisionHandler:(void (^ _Nonnull)(WKNavigationResponsePolicy))decisionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
